# --- Applications ---
cask 'visual-studio-code'
cask 'raycast'
cask 'alt-tab'
cask 'rectangle'
cask 'oversight'
cask 'spotify'
cask 'sublime-text'
cask 'cursor'
cask 'alacritty'
cask 'jordanbaird-ice'

# --- CLI Tools ---
brew 'tree'
brew 'lf'
brew 'speedtest-cli'
brew 'zip'
brew 'wget'
brew 'tmux'
brew 'direnv'
brew 'starship'
brew 'stow'
brew 'zsh-syntax-highlighting'
brew 'mas'

# --- Fonts ---
cask 'font-fira-code-nerd-font'
